#!/usr/bin/sh
chuck $HOME/music/src/chuck/clock.ck $HOME/music/src/chuck/looper.ck $HOME/music/src/chuck/arrange.ck &
mkdir -p $HOME/music/src/.current
echo $1 > $HOME/music/src/.current/dir
sxhkd -c $HOME/music/src/sxhkd/arrange.sxhkdrc
#oscsend localhost 9669 /start
#$HOME/music/src/ruby/scene.rb 0
